// single-spa-vite-react-example/src/App.tsx
import React, { useState } from "react";
import logo from "/logo.svg";
import "./App.css";
import parsePublicAssetsPath from "./utils/parse-public-assets-path";

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className='App'>
      <header className='App-header'>
        <img
          src={parsePublicAssetsPath(logo)}
          className='App-logo'
          alt='logo'
        />
        <p>Hello Vite2.0 + React!</p>
        <p>
          <button type='button' onClick={() => setCount((count) => count + 1)}>
            count is: {count}
          </button>
        </p>
        <p>
          Edit <code>App.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className='App-link'
            href='https://reactjs.org'
            target='_blank'
            rel='noopener noreferrer'
          >
            Learn React
          </a>
          {" | "}
          <a
            className='App-link'
            href='https://vitejs.dev/guide/features.html'
            target='_blank'
            rel='noopener noreferrer'
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;

// single-spa-vite-vue3-example/src/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import { parsePublicAssetsPath } from "./utils";

import vueLogo from "./assets/vue.svg";
import viteLogo from "./assets/vite.svg";

const logos = {
  vue: parsePublicAssetsPath(vueLogo),
  vite: parsePublicAssetsPath(viteLogo)
};
</script>

<template>
  <div id="main-vue-app">
    <a href="https://vitejs.dev" target="_blank">
      <img :src="logos.vite" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img :src="logos.vue" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue => Madhu freaking ROCKSSS!!" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
